apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-squares-
  labels:
    workflows.argoproj.io/archive-strategy: "false"
spec:
  entrypoint: hello-squares
  serviceAccountName: argo-workflows-executor
  templates:
  - name: hello-squares
    container:
      image: alexgleith/squares:latest
      command: ["/app/square.py"]
      args: ["9"]
